experiment_name: task1_gpt5 

model:
  type: mistral            #model handler type as written in models/__init__.py
  name: mistralai/Mistral-Small-3.2-24B-Instruct-2506  # just as it appears in huggingface

cache_dir: /scratch/ca2627/huggingface #modify to your own cache directory

dataset:
  path: datasets/qa/medarabench.json   #path to dataset JSON file
  instruction_path: prompts/task1.txt  #path to instruction file (default.txt)

task:
  type: mcq                #task 1: mcq or task 2: answer_generation

output:
  predictions_path: results/predictions/task1/test.csv #specify output pred file
  metrics_path: results/metrics/task1/test.json  #specift output pred file

